# Generated by Django 4.2.7 on 2023-11-05 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Student_surname', models.CharField(max_length=255)),
                ('Student_name', models.CharField(max_length=255)),
                ('Student_lastname', models.CharField(max_length=255)),
                ('Student_address', models.CharField(max_length=255)),
                ('Student_phone', models.CharField(max_length=15)),
                ('Course', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Faculty', models.CharField(choices=[('аграрного менеджменту', 'аграрного менеджменту'), ('економіки', 'економіки'), ('інформаційних технологій', 'інформаційних технологій')], max_length=50)),
                ('Student_group', models.CharField(max_length=10)),
                ('isHead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('Subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Hours_per_semester', models.PositiveIntegerField()),
                ('Number_of_semesters', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passing_exams',
            fields=[
                ('Passing_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_of_passing', models.DateField()),
                ('Score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.students')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.subjects')),
            ],
        ),
    ]
